// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,   
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(    
    apiKey: 'AIzaSyB1FmWaXEXL-UGX_mslgIUV6ZPn55BNv9k',   
    appId: '1:449930785734:web:e3995589417c80525d38c7',
    messagingSenderId: '449930785734',
    projectId: 'eclezzia-hpc',
    authDomain: 'eclezzia-hpc.firebaseapp.com',
    storageBucket: 'eclezzia-hpc.firebasestorage.app',   
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1FmWaXEXL-UGX_mslgIUV6ZPn55BNv9k',   
    appId: '1:449930785734:android:6c37d5bfd4e4d5795d38c7',
    messagingSenderId: '449930785734',
    projectId: 'eclezzia-hpc',
    storageBucket: 'eclezzia-hpc.firebasestorage.app',   
  );

  static const FirebaseOptions ios = FirebaseOptions(    
    apiKey: 'AIzaSyB1FmWaXEXL-UGX_mslgIUV6ZPn55BNv9k',   
    appId: '1:449930785734:ios:6f699ae41d010a485d38c7',  
    messagingSenderId: '449930785734',
    projectId: 'eclezzia-hpc',
    storageBucket: 'eclezzia-hpc.firebasestorage.app',   
    iosBundleId: 'com.ndeascloud.hpc.hpcapp',
  );
}
